/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DebateContract } from "./DebateContract";
export type { DebateContractV2 } from "./DebateContractV2";
export type { DebateToken } from "./DebateToken";
export type { MockUSDC } from "./MockUSDC";
